# Makefile for calculate.cpp                                                                                                                 
# This command will "clean" out the directory of any output files

clean:
	rm *.out

# This command will compile the source code when you run                                                                                      
compile:
	g++ calculate.cpp -o calculate.out

# This command will run the Program                                                                                                           
run:
	./calculate.out
