# November 29, 2022
# CPSC 1070
# This file is the makefile that I use to compile, run and clean code.

# This command will compile the source code when you run
compile:
	cc LinkedList.c -c
	cc driver.c LinkedList.o -o driver.out
run:
	./driver.out
# this command will delete all files ending in .o or .out
clean:
	rm *.o
	rm *.out
