# December 5, 2022
# CPSC 1070
# Project 4 Wordle Assistant
# This file is the makefile that I use to compile, run and clean code.

# This command will compile the source code when you run
compile:
	cc Wordle.c -c
	cc Project-4.c Wordle.o -o Project-4.out
run:
	./Project-4.out
# this command will delete all files ending in .o or .out
clean:
	rm *.o
	rm *.out
